### ISSUE TITLE
Firefox ESR incorrectly marked as out-of-date in comfig app

### ISSUE THREAD

**Issue by TorutheRedFox** [mastercomfig/comfig-app#71]
115.14.0 is the latest release of ESR as of writing this post and it's marked as out-of-date by the app. This is incorrect.

**Comment by mastercoms** [comment]
https://github.com/mastercomfig/comfig-app/issues/60#issuecomment-2094554632

To add onto this, ESR isn't in my testing set of browsers. I don't purposefully try to use the absolute latest and break ESR but it's hard to verify everything will work with all the interactions. It's hard for me to justify supporting a browser which is kept out of date on purpose and has such low usage. Thus the warning.

**Comment by TorutheRedFox** [comment]
to my knowledge, ESR is kept up to date with the latest version of gecko and updated security, with it's main purpose being keeping the browser itself on the same version for longer to make enterprise-related stuff work with it better as you don't have to keep up with it as much

that also has the side effect of making ESR good for modding

**Comment by mastercoms** [comment]
ESR does not get new features. It gets fixes, sure, but for one example, I know that Firefox ESR was broken with comfig downloads for quite some time due to missing TransformStream support which was needed to produce ZIP files. It's fixed now, of course, but again, I can't always guarantee that Firefox ESR will work.  Keeping the browser "on the same version for longer" is not just a version number, but it means that it doesn't get these features and can break websites which rely on modern web features.

> Extended Support Release (ESR) receives major updates on average every 52 weeks with minor updates such as crash fixes, security fixes and policy updates as needed

https://support.mozilla.org/en-US/kb/choosing-firefox-update-channel

This means Firefox ESR will be a year out of date in some cases. I can't really manage to support it.
